"""AUTO-GENERATED scope hints — regenerate via scripts/generate_falcon_modules.py."""

GENERATED_SCOPE_REQUIREMENTS = {
    "ActionUpdateCount": ['Quarantined Files:read'],
    "ArchiveDeleteV1": ['Sample Uploads:write'],
    "ArchiveGetV1": ['Sample Uploads:read'],
    "ArchiveListV1": ['Sample Uploads:read'],
    "AzureDownloadCertificate": ['CSPM registration:read'],
    "AzureRefreshCertificate": ['CSPM registration:write'],
    "BatchGetCmdStatus": ['Real time response:read'],
    "BulkInstallParsers": ['NGSIEM:write'],
    "CaseDownloadAttachment": ['Message Center:read'],
    "CombinedBaseImages": ['Falcon Container Image:read'],
    "CombinedDetections": ['Snapshot:read'],
    "CombinedDevicesByFilter": ['Hosts:read'],
    "CombinedHiddenDevicesByFilter": ['Hosts:read'],
    "CombinedImageByVulnerabilityCount": ['Falcon Container Image:read'],
    "CombinedImageDetail": ['Falcon Container Image:read'],
    "CombinedImageIssuesSummary": ['Falcon Container Image:read'],
    "CombinedImageVulnerabilitySummary": ['Falcon Container Image:read'],
    "CombinedImagesFindings": ['Kubernetes Protection:read'],
    "CombinedNodesFindings": ['Kubernetes Protection:read'],
    "CombinedReleaseNotesV1": ['Deployment Coordinator:read'],
    "CombinedReleasesV1Mixin0": ['Deployment Coordinator:read'],
    "CombinedUserRolesV2": ['User Management:read'],
    "ConnectCSPMGCPAccount": ['CSPM registration:write'],
    "ConnectD4CGCPAccount": ['D4C registration:write'],
    "CreateAWSAccount": ['Kubernetes Protection:write'],
    "CreateActionsV1": ['Monitoring rules (Falcon Intelligence Recon):write'],
    "CreateAzureSubscription": ['Kubernetes Protection:write'],
    "CreateBaseImagesEntities": ['Falcon Container Image:write'],
    "CreateCSPMAwsAccount": ['CSPM registration:write'],
    "CreateCSPMAzureAccount": ['CSPM registration:write'],
    "CreateCSPMAzureManagementGroup": ['CSPM registration:write'],
    "CreateCSPMGCPAccount": ['CSPM registration:write'],
    "CreateCloudGroupExternal": ['Cloud security:write'],
    "CreateComplianceControl": ['Cloud Security Policies:write'],
    "CreateComplianceFramework": ['Cloud Security Policies:write'],
    "CreateD4CAwsAccount": ['D4C registration:write'],
    "CreateD4CGCPAccount": ['D4C registration:write'],
    "CreateDeploymentEntity": ['Snapshot:write'],
    "CreateDiscoverCloudAzureAccount": ['D4C registration:write'],
    "CreateExecutorNode": ['ASPM:write'],
    "CreateExportJobsV1": ['Monitoring rules (Falcon Intelligence Recon):write'],
    "CreateIntegration": ['ASPM:write'],
    "CreateIntegrationTask": ['ASPM:write'],
    "CreateOrUpdateAWSSettings": ['AWS accounts:write'],
    "CreateParser": ['NGSIEM:write'],
    "CreatePolicies": ['Falcon Container Image:write'],
    "CreatePolicyGroups": ['Falcon Container Image:write'],
    "CreateRegistryEntities": ['Falcon Container Image:write'],
    "CreateRuleMixin0": ['Cloud Security Policies:write'],
    "CreateRuleOverride": ['Cloud Security Policies:write'],
    "CreateSavedSearchesDynamicExecuteV1": ['App Logs:write'],
    "CreateSavedSearchesExecuteV1": ['App Logs:write'],
    "CreateSavedSearchesIngestV1": ['App Logs:write'],
    "CreateSuppressionRule": ['Cloud Security Policies:write'],
    "CreateUser": ['User Management:write'],
    "DeleteAWSAccounts": ['AWS accounts:write'],
    "DeleteAWSAccountsMixin0": ['Kubernetes Protection:write'],
    "DeleteActionV1": ['Monitoring rules (Falcon Intelligence Recon):write'],
    "DeleteAzureSubscription": ['Kubernetes Protection:write'],
    "DeleteBaseImages": ['Falcon Container Image:write'],
    "DeleteCSPMAwsAccount": ['CSPM registration:write'],
    "DeleteCSPMAzureAccount": ['CSPM registration:write'],
    "DeleteCSPMAzureManagementGroup": ['CSPM registration:write'],
    "DeleteCSPMGCPAccount": ['CSPM registration:write'],
    "DeleteCloudGroupsExternal": ['Cloud security:write'],
    "DeleteComplianceControl": ['Cloud Security Policies:write'],
    "DeleteComplianceFramework": ['Cloud Security Policies:write'],
    "DeleteD4CAwsAccount": ['D4C registration:write'],
    "DeleteD4CGCPAccount": ['D4C registration:write'],
    "DeleteDashboard": ['NGSIEM:write'],
    "DeleteExecutorNode": ['ASPM:write'],
    "DeleteExportJobsV1": ['Monitoring rules (Falcon Intelligence Recon):write'],
    "DeleteFile": ['QuickScan Pro:write'],
    "DeleteImageDetails": ['Falcon Container Image:write'],
    "DeleteIntegration": ['ASPM:write'],
    "DeleteIntegrationTask": ['ASPM:write'],
    "DeleteLookupFile": ['NGSIEM:write'],
    "DeleteObject": ['Custom Storage:write'],
    "DeleteParser": ['NGSIEM:write'],
    "DeletePolicy": ['Falcon Container Image:write'],
    "DeletePolicyGroup": ['Falcon Container Image:write'],
    "DeleteRegistryEntities": ['Falcon Container Image:write'],
    "DeleteReport": ['Falconx Sandbox:write'],
    "DeleteRuleMixin0": ['Cloud Security Policies:write'],
    "DeleteRuleOverride": ['Cloud Security Policies:write'],
    "DeleteSampleV2": ['Falconx Sandbox:write'],
    "DeleteSampleV3": ['Sample Uploads:write'],
    "DeleteSavedQuery": ['NGSIEM:write'],
    "DeleteScanResult": ['QuickScan Pro:write'],
    "DeleteSuppressionRules": ['Cloud Security Policies:write'],
    "DeleteTags": ['ASPM:write'],
    "DeleteUser": ['User Management:write'],
    "DeleteVersionedObject": ['Custom Storage:write'],
    "DescribeCollections": ['Custom Storage:write'],
    "DiscoverCloudAzureDownloadCertificate": ['D4C registration:read'],
    "DownloadExportFile": ['Falcon Container Image:read'],
    "DownloadExportFileMixin0": ['Falcon Container Image:read'],
    "DownloadFeedArchive": ['Falcon Indicator Graph:read'],
    "DownloadFile": ['Tools Download:read'],
    "DownloadSensorInstallerByIdV3": ['Sensor Download:read'],
    "EnumerateFile": ['Tools Download:read'],
    "ExecuteCommand": ['API integrations:write'],
    "ExecuteCommandProxy": ['API integrations:write'],
    "ExecuteFunctionData": ['ASPM:read'],
    "ExecuteFunctionDataCount": ['ASPM:write'],
    "ExecuteFunctionDataQuery": ['ASPM:read'],
    "ExecuteFunctionDataQueryCount": ['ASPM:read'],
    "ExecuteFunctions": ['ASPM:read'],
    "ExecuteFunctionsCount": ['ASPM:write'],
    "ExecuteFunctionsOvertime": ['ASPM:read'],
    "ExecuteFunctionsQuery": ['ASPM:read'],
    "ExecuteFunctionsQueryCount": ['ASPM:read'],
    "ExecuteFunctionsQueryOvertime": ['ASPM:read'],
    "ExecuteQuery": ['ASPM:write'],
    "ExternalCreateConnectorConfig": ['NGSIEM:write'],
    "ExternalDeleteConnectorConfigs": ['NGSIEM:write'],
    "ExternalGetDataConnectionByID": ['NGSIEM:read'],
    "ExternalListConnectorConfigs": ['NGSIEM:read'],
    "ExternalPatchConnectorConfig": ['NGSIEM:write'],
    "ExternalUpdateDataConnection": ['NGSIEM:write'],
    "ExtractionCreateV1": ['Sample Uploads:write'],
    "ExtractionGetV1": ['Sample Uploads:read'],
    "ExtractionListV1": ['Sample Uploads:read'],
    "FetchFilesDownloadInfoV2": ['Tools Download:read'],
    "FindContainersByContainerRunTimeVersion": ['Kubernetes Protection:read'],
    "FindContainersCountAffectedByZeroDayVulnerabilities": ['Kubernetes Protection:read'],
    "GetAWSAccounts": ['AWS accounts:read'],
    "GetAWSAccountsMixin0": ['Kubernetes Protection:read'],
    "GetAWSSettings": ['AWS accounts:read'],
    "GetActionsV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetActivityMonitorV3": ['Falcon Shield:read'],
    "GetAggregateFiles": ['Quarantined Files:read'],
    "GetAlertsV3": ['Falcon Shield:read'],
    "GetAppInventory": ['Falcon Shield:read'],
    "GetAppInventoryUsers": ['Falcon Shield:read'],
    "GetArchiveExport": ['CAO Hunting:read'],
    "GetArtifacts": ['Falconx Sandbox:read'],
    "GetAssetInventoryV3": ['Falcon Shield:read'],
    "GetAvailableRoleIds": ['User Management:read'],
    "GetAzureInstallScript": ['Kubernetes Protection:read'],
    "GetAzureTenantConfig": ['Kubernetes Protection:read'],
    "GetAzureTenantIDs": ['Kubernetes Protection:read'],
    "GetBehaviorDetections": ['CSPM registration:read'],
    "GetCSPMAwsAccount": ['CSPM registration:read'],
    "GetCSPMAwsAccountScriptsAttachment": ['CSPM registration:read'],
    "GetCSPMAwsConsoleSetupURLs": ['CSPM registration:read'],
    "GetCSPMAzureAccount": ['CSPM registration:read'],
    "GetCSPMAzureManagementGroup": ['CSPM registration:read'],
    "GetCSPMAzureUserScriptsAttachment": ['CSPM registration:read'],
    "GetCSPMCGPAccount": ['CSPM registration:read'],
    "GetCSPMGCPAccount": ['CSPM registration:read'],
    "GetCSPMGCPServiceAccountsExt": ['CSPM registration:read'],
    "GetCSPMGCPUserScriptsAttachment": ['D4C registration:read'],
    "GetCSPMGCPValidateAccountsExt": ['CSPM registration:read'],
    "GetCSPMPoliciesDetails": ['CSPM registration:read'],
    "GetCSPMPolicy": ['CSPM registration:read'],
    "GetCSPMPolicySettings": ['CSPM registration:read'],
    "GetCSPMScanSchedule": ['CSPM registration:read'],
    "GetCloudSecurityIntegrationState": ['ASPM:read'],
    "GetClusters": ['Kubernetes Protection:read'],
    "GetCombinedCloudClusters": ['Kubernetes Protection:read'],
    "GetCombinedImages": ['Falcon Container Image:read'],
    "GetCombinedPluginConfigs": ['API integrations:read'],
    "GetComplianceControls": ['Cloud Security Policies:read'],
    "GetComplianceFrameworks": ['Cloud Security Policies:read'],
    "GetConfigurationDetectionEntities": ['CSPM registration:read'],
    "GetConfigurationDetectionIDsV2": ['CSPM registration:read'],
    "GetConfigurationDetections": ['CSPM registration:read'],
    "GetCredentials": ['Falcon Container Image:read'],
    "GetCredentialsIAC": ['Snapshot:read'],
    "GetCredentialsMixin0": ['Snapshot:read'],
    "GetD4CAWSAccountScriptsAttachment": ['D4C registration:read'],
    "GetD4CAwsAccount": ['D4C registration:read'],
    "GetD4CAwsConsoleSetupURLs": ['D4C registration:read'],
    "GetD4CCGPAccount": ['D4C registration:read'],
    "GetD4CGCPServiceAccountsExt": ['D4C registration:read'],
    "GetD4CGCPUserScripts": ['D4C registration:read'],
    "GetD4CGCPUserScriptsAttachment": ['D4C registration:read'],
    "GetDashboardTemplate": ['NGSIEM:read'],
    "GetDeliverySettings": ['Channel File:read'],
    "GetDeploymentsExternalV1": ['Deployment Coordinator:read'],
    "GetDeviceCountCollectionQueriesByFilter": ['Falcon Complete Dashboard:read'],
    "GetDeviceDetailsV2": ['Hosts:read'],
    "GetDeviceInventoryV3": ['Falcon Shield:read'],
    "GetDiscoverCloudAzureAccount": ['D4C registration:read'],
    "GetDiscoverCloudAzureTenantIDs": ['D4C registration:read'],
    "GetDiscoverCloudAzureUserScripts": ['D4C registration:read'],
    "GetDiscoverCloudAzureUserScriptsAttachment": ['D4C registration:read'],
    "GetDriftIndicatorsValuesByDate": ['Falcon Container Image:read'],
    "GetEnrichedAsset": ['Cloud Security Policies:read'],
    "GetEntityIDsByQueryPOSTV2": ['Deployment Coordinator:read'],
    "GetEvaluationResult": ['Cloud Security Policies:read'],
    "GetEventsBody": ['Tailored Intelligence:read'],
    "GetExecutorNodes": ['ASPM:read'],
    "GetExecutorNodesMetadata": ['ASPM:read'],
    "GetExportJobsV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetFileContentForExportJobsV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetGroupHierarchy": ['ASPM:read'],
    "GetGroupsV2": ['ASPM:read'],
    "GetHelmValuesYaml": ['Kubernetes Protection:read'],
    "GetHorizonD4CScripts": ['D4C registration:read'],
    "GetHuntingGuides": ['CAO Hunting:read'],
    "GetIOAEvents": ['CSPM registration:read'],
    "GetIOAUsers": ['CSPM registration:read'],
    "GetImageAssessmentReport": ['Falcon Container Image:read'],
    "GetIndicatorsReport": ['IOC Management:read'],
    "GetIntegrationTasksAdmin": ['ASPM:read'],
    "GetIntegrationTasksMetadata": ['ASPM:read'],
    "GetIntegrationTasksV2": ['ASPM:read'],
    "GetIntegrationTypes": ['ASPM:read'],
    "GetIntegrationsV2": ['ASPM:read'],
    "GetIntegrationsV3": ['Falcon Shield:read'],
    "GetIntelActorEntities": ['Falcon Intelligence:read'],
    "GetIntelIndicatorEntities": ['Falcon Intelligence:read'],
    "GetIntelReportEntities": ['Falcon Intelligence:read'],
    "GetIntelReportPDF": ['Falcon Intelligence:read'],
    "GetIntelRuleEntities": ['Falcon Intelligence:read'],
    "GetIntelRuleFile": ['Falcon Intelligence:read'],
    "GetIntelligenceQueries": ['CAO Hunting:read'],
    "GetLatestIntelRuleFile": ['Falcon Intelligence:read'],
    "GetLocations": ['Kubernetes Protection:read'],
    "GetLookupFile": ['NGSIEM:read'],
    "GetLookupFromPackageV1": ['NGSIEM:read'],
    "GetLookupFromPackageWithNamespaceV1": ['NGSIEM:read'],
    "GetLookupV1": ['NGSIEM:read'],
    "GetMalQueryDownloadV1": ['Malquery:read'],
    "GetMalQueryEntitiesSamplesFetchV1": ['Malquery:read'],
    "GetMalwareEntities": ['Falcon Intelligence:read'],
    "GetMalwareMitreReport": ['Falcon Intelligence:read'],
    "GetMemoryDump": ['Falconx Sandbox:read'],
    "GetMemoryDumpExtractedStrings": ['Falconx Sandbox:read'],
    "GetMemoryDumpHexDump": ['Falconx Sandbox:read'],
    "GetMetricsV3": ['Falcon Shield:read'],
    "GetNotificationsDetailedTranslatedV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetNotificationsDetailedV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetNotificationsExposedDataRecordsV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetNotificationsTranslatedV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "GetObject": ['Custom Storage:read'],
    "GetObjectMetadata": ['Custom Storage:read'],
    "GetParser": ['NGSIEM:read'],
    "GetParserTemplate": ['NGSIEM:read'],
    "GetReportByReference": ['Falcon Container Image:read'],
    "GetReportByScanID": ['Falcon Container Image:read'],
    "GetRoles": ['User Management:read'],
    "GetRule": ['Cloud Security Policies:read'],
    "GetRuleInputSchema": ['Cloud Security Policies:read'],
    "GetRuleOverride": ['Cloud Security Policies:read'],
    "GetRuntimeDetectionsCombinedV2": ['Cloud Security API Detections:read'],
    "GetSampleV2": ['Falconx Sandbox:read'],
    "GetSampleV3": ['Sample Uploads:read'],
    "GetSavedQueryTemplate": ['NGSIEM:read'],
    "GetSavedSearchesExecuteV1": ['App Logs:read'],
    "GetSavedSearchesJobResultsDownloadV1": ['App Logs:read'],
    "GetScanReport": ['Snapshot:read'],
    "GetScanResult": ['QuickScan Pro:read'],
    "GetScans": ['Quick Scan:read'],
    "GetSecurityCheckAffectedV3": ['Falcon Shield:read'],
    "GetSecurityCheckComplianceV3": ['Falcon Shield:read'],
    "GetSecurityChecksV3": ['Falcon Shield:read'],
    "GetSensorDetails": ['Identity Protection GraphQL:read'],
    "GetSensorInstallersByQueryV3": ['Sensor Download:read'],
    "GetSensorUsageHourly": ['Sensor Usage:read'],
    "GetServiceViolationTypes": ['ASPM:read'],
    "GetServicesCount": ['ASPM:read'],
    "GetStaticScripts": ['Kubernetes Protection:read'],
    "GetSubmissions": ['Falconx Sandbox:read'],
    "GetSupportedSaasV3": ['Falcon Shield:read'],
    "GetSuppressionRules": ['Cloud Security Policies:read'],
    "GetSystemLogsV3": ['Falcon Shield:read'],
    "GetSystemUsersV3": ['Falcon Shield:read'],
    "GetTags": ['ASPM:read'],
    "GetUserInventoryV3": ['Falcon Shield:read'],
    "GetUserRoleIds": ['User Management:read'],
    "GetUsersV2": ['ASPM:read'],
    "GetVersionedObject": ['Custom Storage:read'],
    "GetVersionedObjectMetadata": ['Custom Storage:read'],
    "GetVulnerabilities": ['Falcon Intelligence:read'],
    "GrantUserRoleIds": ['User Management:write'],
    "GroupContainersByManaged": ['Kubernetes Protection:read'],
    "HeadImageScanInventory": ['Falcon Container Image:write'],
    "ITAutomationCreatePolicy": ['Falcon for IT:write'],
    "ITAutomationCreateScheduledTask": ['Falcon for IT:write'],
    "ITAutomationCreateTask": ['Falcon for IT:write'],
    "ITAutomationCreateTaskGroup": ['Falcon for IT:write'],
    "ITAutomationCreateUserGroup": ['Falcon for IT:write'],
    "ITAutomationDeletePolicy": ['Falcon for IT:write'],
    "ITAutomationDeleteScheduledTasks": ['Falcon for IT:write'],
    "ITAutomationDeleteTask": ['Falcon for IT:write'],
    "ITAutomationDeleteTaskGroups": ['Falcon for IT:write'],
    "ITAutomationDeleteUserGroup": ['Falcon for IT:write'],
    "ITAutomationGetAssociatedTasks": ['Falcon for IT:read'],
    "ITAutomationGetExecutionResultsSearchStatus": ['Falcon for IT:read'],
    "ITAutomationGetPolicies": ['Falcon for IT:read'],
    "ITAutomationGetScheduledTasks": ['Falcon for IT:read'],
    "ITAutomationGetTaskGroups": ['Falcon for IT:read'],
    "ITAutomationGetTaskGroupsByQuery": ['Falcon for IT:read'],
    "ITAutomationGetUserGroup": ['Falcon for IT:read'],
    "ITAutomationRerunTaskExecution": ['Falcon for IT:write'],
    "ITAutomationRunLiveQuery": ['Falcon for IT:write'],
    "ITAutomationSearchScheduledTasks": ['Falcon for IT:read'],
    "ITAutomationSearchTaskExecutions": ['Falcon for IT:read'],
    "ITAutomationSearchTaskGroups": ['Falcon for IT:read'],
    "ITAutomationSearchTasks": ['Falcon for IT:read'],
    "ITAutomationSearchUserGroup": ['Falcon for IT:read'],
    "ITAutomationStartExecutionResultsSearch": ['Falcon for IT:write'],
    "ITAutomationStartTaskExecution": ['Falcon for IT:write'],
    "ITAutomationUpdatePolicies": ['Falcon for IT:write'],
    "ITAutomationUpdatePoliciesPrecedence": ['Falcon for IT:write'],
    "ITAutomationUpdatePolicyHostGroups": ['Falcon for IT:write'],
    "ITAutomationUpdateScheduledTask": ['Falcon for IT:write'],
    "ITAutomationUpdateTask": ['Falcon for IT:write'],
    "ITAutomationUpdateTaskGroup": ['Falcon for IT:write'],
    "ITAutomationUpdateUserGroup": ['Falcon for IT:write'],
    "ImageMatchesPolicy": ['Falcon Container Image:read'],
    "InstallParser": ['NGSIEM:write'],
    "IntegrationBuilderEndTransactionV3": ['Falcon Shield:write'],
    "IntegrationBuilderGetStatusV3": ['Falcon Shield:read'],
    "IntegrationBuilderResetV3": ['Falcon Shield:write'],
    "IntegrationBuilderUploadV3": ['Falcon Shield:write'],
    "LaunchExportJob": ['Falcon Container Image:write'],
    "LaunchExportJobMixin0": ['Falcon Container Image:write'],
    "LaunchScan": ['QuickScan Pro:write'],
    "ListAzureAccounts": ['Kubernetes Protection:read'],
    "ListCloudGroupIDsExternal": ['Cloud security:read'],
    "ListCloudGroupsByIDExternal": ['Cloud security:read'],
    "ListCloudGroupsExternal": ['Cloud security:read'],
    "ListCollections": ['Custom Storage:read'],
    "ListFeedTypes": ['Falcon Indicator Graph:read'],
    "ListObjects": ['Custom Storage:read'],
    "ListObjectsByVersion": ['Custom Storage:read'],
    "ListReposV1": ['App Logs:read'],
    "ListViewV1": ['App Logs:read'],
    "LookupIndicators": ['Falcon Indicator Graph:read'],
    "PatchAzureServicePrincipal": ['Kubernetes Protection:write'],
    "PatchCSPMAwsAccount": ['CSPM registration:write'],
    "PolicyChecks": ['Falcon Container Image:read'],
    "PostCombinedAlertsV1": ['Alerts:write'],
    "PostDeliverySettings": ['Channel File:write'],
    "PostGroupV2": ['ASPM:write'],
    "PostImageScanInventory": ['Falcon Container Image:write'],
    "PostMalQueryEntitiesSamplesMultidownloadV1": ['Malquery:write'],
    "PostMalQueryFuzzySearchV1": ['Malquery:write'],
    "PostMitreAttacks": ['Falcon Intelligence:write'],
    "PostSearchKubernetesIOMEntities": ['Kubernetes Protection:write'],
    "PreviewRuleV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "ProvisionAWSAccounts": ['AWS accounts:write'],
    "PutObject": ['Custom Storage:write'],
    "QueryAWSAccounts": ['AWS accounts:read'],
    "QueryAWSAccountsForIDs": ['AWS accounts:read'],
    "QueryActionsV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "QueryAlertIdsByFilterV2": ['Falcon Complete Dashboard:read'],
    "QueryAllowListFilter": ['Falcon Complete Dashboard:read'],
    "QueryBlockListFilter": ['Falcon Complete Dashboard:read'],
    "QueryComplianceControls": ['Cloud Security Policies:read'],
    "QueryComplianceFrameworks": ['Cloud Security Policies:read'],
    "QueryDeviceLoginHistoryV2": ['Hosts:read'],
    "QueryEscalationsFilter": ['Falcon Complete Dashboard:read'],
    "QueryExportJobs": ['Falcon Container Image:read'],
    "QueryExportJobsMixin0": ['Falcon Container Image:read'],
    "QueryFeedArchives": ['Falcon Indicator Graph:read'],
    "QueryGetNetworkAddressHistoryV1": ['Hosts:read'],
    "QueryHiddenDevices": ['Hosts:read'],
    "QueryIncidentIdsByFilter": ['Falcon Complete Dashboard:read'],
    "QueryIntelActorIds": ['Falcon Intelligence:read'],
    "QueryIntelIndicatorIds": ['Falcon Intelligence:read'],
    "QueryIntelReportIds": ['Falcon Intelligence:read'],
    "QueryIntelRuleIds": ['Falcon Intelligence:read'],
    "QueryMalware": ['Falcon Intelligence:read'],
    "QueryMalwareEntities": ['Falcon Intelligence:read'],
    "QueryMitreAttacks": ['Falcon Intelligence:read'],
    "QueryMitreAttacksForMalware": ['Falcon Intelligence:read'],
    "QueryNotificationsExposedDataRecordsV1": ['Monitoring rules (Falcon Intelligence Recon):read'],
    "QueryReleaseNotesV1": ['Deployment Coordinator:read'],
    "QueryRemediationsFilter": ['Falcon Complete Dashboard:read'],
    "QueryRule": ['Cloud Security Policies:read'],
    "QuerySampleV1": ['Falconx Sandbox:read'],
    "QueryScanResults": ['QuickScan Pro:read'],
    "QuerySensorsByFilter": ['Identity Protection GraphQL:read'],
    "QuerySubmissions": ['Falconx Sandbox:read'],
    "QuerySubmissionsMixin0": ['Quick Scan:read'],
    "QuerySuppressionRules": ['Cloud Security Policies:read'],
    "QueryVulnerabilities": ['Falcon Intelligence:read'],
    "RTRAuditSessions": ['Real time response:read'],
    "RTR_CheckActiveResponderCommandStatus": ['Real time response:read'],
    "RTR_CheckAdminCommandStatus": ['Real time response (admin):read'],
    "RTR_DeleteFileV2": ['Real time response:write'],
    "RTR_DeleteQueuedSession": ['Real time response:write'],
    "RTR_ExecuteActiveResponderCommand": ['Real time response:write'],
    "RTR_ExecuteAdminCommand": ['Real time response (admin):write'],
    "RTR_GetExtractedFileContents": ['Real time response:read'],
    "RTR_GetPutFileContents": ['Real time response (admin):read'],
    "RTR_ListQueuedSessions": ['Real time response:write'],
    "ReadClusterCombinedV2": ['Kubernetes Protection:read'],
    "ReadClusterCount": ['Kubernetes Protection:read'],
    "ReadClusterEnrichment": ['Kubernetes Protection:read'],
    "ReadClustersByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadClustersByKubernetesVersionCount": ['Kubernetes Protection:read'],
    "ReadClustersByStatusCount": ['Kubernetes Protection:read'],
    "ReadCombinedDetections": ['Cloud Security API Detections:read'],
    "ReadCombinedImagesExport": ['Falcon Container Image:read'],
    "ReadCombinedVulnerabilitiesDetails": ['Falcon Container Image:read'],
    "ReadCombinedVulnerabilitiesInfo": ['Falcon Container Image:read'],
    "ReadContainerAlertsCount": ['Alerts:read'],
    "ReadContainerAlertsCountBySeverity": ['Alerts:read'],
    "ReadContainerCountByRegistry": ['Kubernetes Protection:read'],
    "ReadContainerEnrichment": ['Kubernetes Protection:read'],
    "ReadContainerImageDetectionsCountByDate": ['Kubernetes Protection:read'],
    "ReadContainerImagesByMostUsed": ['Kubernetes Protection:read'],
    "ReadContainerImagesByState": ['Kubernetes Protection:read'],
    "ReadContainerVulnerabilitiesBySeverityCount": ['Kubernetes Protection:read'],
    "ReadContainersByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadContainersSensorCoverage": ['Kubernetes Protection:read'],
    "ReadDeploymentCombined": ['Kubernetes Protection:read'],
    "ReadDeploymentCount": ['Kubernetes Protection:read'],
    "ReadDeploymentEnrichment": ['Kubernetes Protection:read'],
    "ReadDeploymentsByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadDeploymentsCombined": ['Snapshot:read'],
    "ReadDeploymentsEntities": ['Snapshot:read'],
    "ReadDetections": ['Cloud Security API Detections:read'],
    "ReadDetectionsCount": ['Cloud Security API Detections:read'],
    "ReadDetectionsCountBySeverity": ['Cloud Security API Detections:read'],
    "ReadDetectionsCountByType": ['Cloud Security API Detections:read'],
    "ReadDistinctContainerImageCount": ['Kubernetes Protection:read'],
    "ReadDriftIndicatorEntities": ['Falcon Container Image:read'],
    "ReadDriftIndicatorsCount": ['Falcon Container Image:read'],
    "ReadExportJobs": ['Falcon Container Image:read'],
    "ReadExportJobsMixin0": ['Falcon Container Image:read'],
    "ReadImageVulnerabilities": ['Falcon Container Image:read'],
    "ReadKubernetesIomByDateRange": ['Kubernetes Protection:read'],
    "ReadKubernetesIomCount": ['Kubernetes Protection:read'],
    "ReadKubernetesIomEntities": ['Kubernetes Protection:read'],
    "ReadNamespaceCount": ['Kubernetes Protection:read'],
    "ReadNamespacesByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadNodeCombined": ['Kubernetes Protection:read'],
    "ReadNodeCount": ['Kubernetes Protection:read'],
    "ReadNodeEnrichment": ['Kubernetes Protection:read'],
    "ReadNodesByCloudCount": ['Kubernetes Protection:read'],
    "ReadNodesByContainerEngineVersionCount": ['Kubernetes Protection:read'],
    "ReadNodesByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadPackagesByFixableVulnCount": ['Falcon Container Image:read'],
    "ReadPackagesByImageCount": ['Falcon Container Image:read'],
    "ReadPackagesByVulnCount": ['Falcon Container Image:read'],
    "ReadPackagesCombinedExport": ['Falcon Container Image:read'],
    "ReadPackagesCombinedV2": ['Falcon Container Image:read'],
    "ReadPackagesCountByZeroDay": ['Falcon Container Image:read'],
    "ReadPodCombined": ['Kubernetes Protection:read'],
    "ReadPodCount": ['Kubernetes Protection:read'],
    "ReadPodEnrichment": ['Kubernetes Protection:read'],
    "ReadPodsByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadPolicies": ['Falcon Container Image:read'],
    "ReadPolicyExclusions": ['Falcon Container Image:read'],
    "ReadPolicyGroups": ['Falcon Container Image:read'],
    "ReadRegistryEntities": ['Falcon Container Image:read'],
    "ReadRegistryEntitiesByUUID": ['Falcon Container Image:read'],
    "ReadRequestBody": ['Foundry Function:read'],
    "ReadRunningContainerImages": ['Kubernetes Protection:read'],
    "ReadUnidentifiedContainersByDateRangeCount": ['Kubernetes Protection:read'],
    "ReadUnidentifiedContainersCount": ['Kubernetes Protection:read'],
    "ReadVulnerabilitiesByImageCount": ['Falcon Container Image:read'],
    "ReadVulnerabilitiesPublicationDate": ['Falcon Container Image:read'],
    "ReadVulnerabilityCount": ['Falcon Container Image:read'],
    "ReadVulnerabilityCountByActivelyExploited": ['Falcon Container Image:read'],
    "ReadVulnerabilityCountByCPSRating": ['Falcon Container Image:read'],
    "ReadVulnerabilityCountByCVSSScore": ['Falcon Container Image:read'],
    "ReadVulnerabilityCountBySeverity": ['Falcon Container Image:read'],
    "ReadVulnerableContainerImageCount": ['Kubernetes Protection:read'],
    "RegenerateAPIKey": ['Kubernetes Protection:write'],
    "RegisterCspmSnapshotAccount": ['Snapshot:write'],
    "RenameSectionComplianceFramework": ['Cloud Security Policies:write'],
    "ReplaceControlRules": ['Cloud Security Policies:write'],
    "RequestDeviceEnrollmentV4": ['Mobile enrollment:write'],
    "RetrieveEmailsByCID": ['User Management:read'],
    "RetrieveUser": ['User Management:read'],
    "RetrieveUserUUID": ['User Management:read'],
    "RetrieveUserUUIDsByCID": ['User Management:read'],
    "RevokeUserRoleIds": ['User Management:write'],
    "ScanSamples": ['Quick Scan:write'],
    "SearchAndReadContainerAlerts": ['Alerts:read'],
    "SearchAndReadDriftIndicatorEntities": ['Falcon Container Image:read'],
    "SearchAndReadKubernetesIomEntities": ['Kubernetes Protection:read'],
    "SearchAndReadUnidentifiedContainers": ['Kubernetes Protection:read'],
    "SearchDetections": ['Cloud Security API Detections:read'],
    "SearchDriftIndicators": ['Falcon Container Image:read'],
    "SearchHuntingGuides": ['CAO Hunting:read'],
    "SearchIndicators": ['Falcon Indicator Graph:write'],
    "SearchIntelligenceQueries": ['CAO Hunting:read'],
    "SearchKubernetesIoms": ['Kubernetes Protection:read'],
    "SearchObjects": ['Custom Storage:write'],
    "SearchObjectsByVersion": ['Custom Storage:write'],
    "ServiceNowGetDeployments": ['ASPM:read'],
    "ServiceNowGetServices": ['ASPM:read'],
    "SetCloudSecurityIntegrationState": ['ASPM:write'],
    "TriggerScan": ['Kubernetes Protection:write'],
    "UpdateAWSAccount": ['Kubernetes Protection:write'],
    "UpdateAWSAccounts": ['AWS accounts:write'],
    "UpdateActionV1": ['Monitoring rules (Falcon Intelligence Recon):write'],
    "UpdateCSPMAzureAccount": ['CSPM registration:write'],
    "UpdateCSPMAzureAccountClientID": ['CSPM registration:write'],
    "UpdateCSPMAzureTenantDefaultSubscriptionID": ['CSPM registration:write'],
    "UpdateCSPMGCPAccount": ['CSPM registration:write'],
    "UpdateCSPMGCPServiceAccountsExt": ['CSPM registration:write'],
    "UpdateCSPMPolicySettings": ['CSPM registration:write'],
    "UpdateCSPMScanSchedule": ['CSPM registration:write'],
    "UpdateCloudGroupExternal": ['Cloud security:write'],
    "UpdateComplianceControl": ['Cloud Security Policies:write'],
    "UpdateComplianceFramework": ['Cloud Security Policies:write'],
    "UpdateD4CGCPServiceAccountsExt": ['D4C registration:write'],
    "UpdateDiscoverCloudAzureAccountClientID": ['D4C registration:write'],
    "UpdateExecutorNode": ['ASPM:write'],
    "UpdateIntegration": ['ASPM:write'],
    "UpdateIntegrationTask": ['ASPM:write'],
    "UpdateParser": ['NGSIEM:write'],
    "UpdateParserAutoUpdatePolicy": ['NGSIEM:write'],
    "UpdatePolicies": ['Falcon Container Image:write'],
    "UpdatePolicyExclusions": ['Falcon Container Image:write'],
    "UpdatePolicyGroups": ['Falcon Container Image:write'],
    "UpdatePolicyPrecedence": ['Falcon Container Image:write'],
    "UpdateQfByQuery": ['Quarantined Files:write'],
    "UpdateRegistryEntities": ['Falcon Container Image:write'],
    "UpdateRule": ['Cloud Security Policies:write'],
    "UpdateRuleOverride": ['Cloud Security Policies:write'],
    "UpdateSuppressionRule": ['Cloud Security Policies:write'],
    "UpdateUser": ['User Management:write'],
    "UpsertBusinessApplications": ['ASPM:write'],
    "UpsertTags": ['ASPM:write'],
    "ValidateCSPMGCPServiceAccountExt": ['CSPM registration:write'],
    "VerifyAWSAccountAccess": ['AWS accounts:write'],
    "WorkflowActivitiesContentCombined": ['Workflow:read'],
    "WorkflowDefinitionsAction": ['Workflow:write'],
    "WorkflowExecuteInternal": ['Workflow:write'],
    "WorkflowExecuteSingleNodeV1": ['Workflow:write'],
    "WorkflowSystemDefinitionsDeProvision": ['Workflow:write'],
    "WorkflowSystemDefinitionsPromote": ['Workflow:write'],
    "WorkflowSystemDefinitionsProvision": ['Workflow:write'],
    "action_get_v1": ['IOC Management:read'],
    "action_query_v1": ['IOC Management:read'],
    "admission_control_add_host_groups": ['Kubernetes Protection:write'],
    "admission_control_add_rule_group_custom_rule": ['Kubernetes Protection:write'],
    "admission_control_create_policy": ['Kubernetes Protection:write'],
    "admission_control_create_rule_groups": ['Kubernetes Protection:write'],
    "admission_control_delete_policies": ['Kubernetes Protection:write'],
    "admission_control_delete_rule_groups": ['Kubernetes Protection:write'],
    "admission_control_get_policies": ['Kubernetes Protection:read'],
    "admission_control_query_policies": ['Kubernetes Protection:read'],
    "admission_control_remove_host_groups": ['Kubernetes Protection:write'],
    "admission_control_remove_rule_group_custom_rule": ['Kubernetes Protection:write'],
    "admission_control_replace_rule_group_selectors": ['Kubernetes Protection:write'],
    "admission_control_set_rule_group_precedence": ['Kubernetes Protection:write'],
    "admission_control_update_policy": ['Kubernetes Protection:write'],
    "admission_control_update_policy_precedence": ['Kubernetes Protection:write'],
    "admission_control_update_rule_groups": ['Kubernetes Protection:write'],
    "blob_download_external_assets": ['Assets:read'],
    "blob_preview_external_assets": ['Assets:read'],
    "cb_exclusions_create_v1": ['Certificate Based Exclusions:write'],
    "cb_exclusions_delete_v1": ['Certificate Based Exclusions:write'],
    "cb_exclusions_get_v1": ['Certificate Based Exclusions:read'],
    "cb_exclusions_query_v1": ['Certificate Based Exclusions:read'],
    "cb_exclusions_update_v1": ['Certificate Based Exclusions:write'],
    "certificates_get_v1": ['Certificate Based Exclusions:read'],
    "cloud_compliance_framework_posture_summaries": ['Cloud Security API Assets:read'],
    "cloud_compliance_rule_posture_summaries": ['Cloud Security API Assets:read'],
    "cloud_registration_aws_create_account": ['Cloud Security AWS Registration:write'],
    "cloud_registration_aws_delete_account": ['Cloud Security AWS Registration:write'],
    "cloud_registration_aws_get_accounts": ['Cloud Security AWS Registration:read'],
    "cloud_registration_aws_query_accounts": ['Cloud Security AWS Registration:read'],
    "cloud_registration_aws_trigger_health_check": ['Cloud Security AWS Registration:write'],
    "cloud_registration_aws_update_account": ['Cloud Security AWS Registration:write'],
    "cloud_registration_aws_validate_accounts": ['Cloud Security AWS Registration:write'],
    "cloud_registration_azure_create_registration": ['Cloud Security Azure Registration:write'],
    "cloud_registration_azure_delete_legacy_subscription": ['Cloud Security Azure Registration:write'],
    "cloud_registration_azure_delete_registration": ['Cloud Security Azure Registration:write'],
    "cloud_registration_azure_download_script": ['Cloud Security Azure Registration:write'],
    "cloud_registration_azure_get_registration": ['Cloud Security Azure Registration:read'],
    "cloud_registration_azure_trigger_health_check": ['Cloud Security Azure Registration:write'],
    "cloud_registration_azure_update_registration": ['Cloud Security Azure Registration:write'],
    "cloud_registration_azure_validate_registration": ['Cloud Security Azure Registration:write'],
    "cloud_registration_gcp_create_registration": ['Cloud Security Google Cloud Registration:write'],
    "cloud_registration_gcp_delete_registration": ['Cloud Security Google Cloud Registration:write'],
    "cloud_registration_gcp_get_entities": ['Cloud Security Google Cloud Registration:read'],
    "cloud_registration_gcp_get_registration": ['Cloud Security Google Cloud Registration:read'],
    "cloud_registration_gcp_put_registration": ['Cloud Security Google Cloud Registration:write'],
    "cloud_registration_gcp_trigger_health_check": ['Cloud Security Google Cloud Registration:write'],
    "cloud_registration_gcp_update_registration": ['Cloud Security Google Cloud Registration:write'],
    "cloud_security_assets_combined_application_findings": ['Cloud Security API Assets:read'],
    "cloud_security_assets_combined_compliance_by_account": ['Cloud Security API Assets:read'],
    "cloud_security_registration_oci_create_account": ['Cloud Security OCI Registration:write'],
    "cloud_security_registration_oci_delete_account": ['Cloud Security OCI Registration:write'],
    "cloud_security_registration_oci_download_script": ['Cloud Security OCI Registration:write'],
    "cloud_security_registration_oci_get_account": ['Cloud Security OCI Registration:read'],
    "cloud_security_registration_oci_rotate_key": ['Cloud Security OCI Registration:write'],
    "cloud_security_registration_oci_update_account": ['Cloud Security OCI Registration:write'],
    "cloud_security_registration_oci_validate_tenancy": ['Cloud Security OCI Registration:write'],
    "combineVulnMetadataExt": ['Risk Platform - Risk:read'],
    "combinedQueryEvaluationLogic": ['Vulnerabilities:read'],
    "combinedSupportedEvaluationExt": ['Vulnerabilities:read'],
    "combined_cloud_risks": ['Cloud security:read'],
    "combined_ecosystem_subsidiaries": ['Assets:read'],
    "combined_file_details_get_v1": ['Case Management:read'],
    "combined_rules_get_v2": ['Correlation Rules:read'],
    "create_network_locations": ['Firewall Management:write'],
    "create_rule_group_validation": ['Firewall Management:write'],
    "cspm_evaluations_combined_iom_by_rule": ['Cloud Security API Detections:read'],
    "cspm_evaluations_iom_entities": ['Cloud Security API Detections:read'],
    "cspm_evaluations_iom_queries": ['Cloud Security API Detections:read'],
    "customer_settings_update": ['Installation Tokens:write'],
    "delete_external_assets": ['Assets:write'],
    "delete_network_locations": ['Firewall Management:write'],
    "delete_scheduled_scans": ['Ods:write'],
    "download_azure_script": ['Cloud Security Azure Registration:read'],
    "entitiesRolesGETV2": ['User Management:write'],
    "entities_access_tags_get_v1": ['Case Management:read'],
    "entities_classification_delete_v2": ['Data Protection:write'],
    "entities_classification_get_v2": ['Data Protection:read'],
    "entities_classification_patch_v2": ['Data Protection:write'],
    "entities_classification_post_v2": ['Data Protection:write'],
    "entities_cloud_application_create": ['Data Protection:write'],
    "entities_cloud_application_delete": ['Data Protection:write'],
    "entities_cloud_application_get": ['Data Protection:read'],
    "entities_cloud_application_patch": ['Data Protection:write'],
    "entities_content_pattern_create": ['Data Protection:write'],
    "entities_content_pattern_delete": ['Data Protection:write'],
    "entities_content_pattern_get": ['Data Protection:read'],
    "entities_content_pattern_patch": ['Data Protection:write'],
    "entities_enterprise_account_create": ['Data Protection:write'],
    "entities_enterprise_account_delete": ['Data Protection:write'],
    "entities_enterprise_account_get": ['Data Protection:read'],
    "entities_enterprise_account_patch": ['Data Protection:write'],
    "entities_fields_get_v1": ['Case Management:read'],
    "entities_file_details_get_v1": ['Case Management:read'],
    "entities_file_details_patch_v1": ['Case Management:write'],
    "entities_file_type_get": ['Data Protection:read'],
    "entities_files_bulk_download_post_v1": ['Case Management:write'],
    "entities_files_delete_v1": ['Case Management:write'],
    "entities_files_download_get_v1": ['Case Management:read'],
    "entities_files_download_post_v1": ['Case Management:write'],
    "entities_get_rtr_file_metadata_post_v1": ['Case Management:read'],
    "entities_latest_rules_get_v1": ['Correlation Rules:read'],
    "entities_local_application_create": ['Data Protection:write'],
    "entities_local_application_delete": ['Data Protection:write'],
    "entities_local_application_get": ['Data Protection:read'],
    "entities_local_application_group_create": ['Data Protection:write'],
    "entities_local_application_group_delete": ['Data Protection:write'],
    "entities_local_application_group_get": ['Data Protection:read'],
    "entities_local_application_group_patch": ['Data Protection:write'],
    "entities_local_application_patch": ['Data Protection:write'],
    "entities_notification_groups_delete_v2": ['Case Management:write'],
    "entities_notification_groups_get_v2": ['Case Management:read'],
    "entities_notification_groups_patch_v2": ['Case Management:write'],
    "entities_notification_groups_post_v2": ['Case Management:write'],
    "entities_perform_action": ['Hosts:write'],
    "entities_policy_delete_v2": ['Data Protection:write'],
    "entities_policy_get_v2": ['Data Protection:read'],
    "entities_policy_patch_v2": ['Data Protection:write'],
    "entities_policy_post_v2": ['Data Protection:write'],
    "entities_policy_precedence_post_v1": ['Data Protection:write'],
    "entities_retrieve_rtr_file_post_v1": ['Case Management:write'],
    "entities_retrieve_rtr_recent_file_post_v1": ['Case Management:write'],
    "entities_rule_versions_delete_v1": ['Correlation Rules:write'],
    "entities_rule_versions_export_post_v1": ['Correlation Rules:write'],
    "entities_rule_versions_import_post_v1": ['Correlation Rules:write'],
    "entities_rule_versions_publish_patch_v1": ['Correlation Rules:write'],
    "entities_rules_ownership_put_v1": ['Correlation Rules:write'],
    "entities_sensitivity_label_create_v2": ['Data Protection:write'],
    "entities_sensitivity_label_delete_v2": ['Data Protection:write'],
    "entities_sensitivity_label_get_v2": ['Data Protection:read'],
    "entities_states_v1": ['Device Content:read'],
    "entities_template_snapshots_get_v1": ['Case Management:read'],
    "entities_templates_get_v1Mixin0": ['Correlation Rules:read'],
    "entities_templates_rules_post_v1": ['Correlation Rules:write'],
    "entities_vertices_get": ['Threatgraph:read'],
    "entities_web_location_create_v2": ['Data Protection:write'],
    "entities_web_location_delete_v2": ['Data Protection:write'],
    "entities_web_location_get_v2": ['Data Protection:read'],
    "entities_web_location_patch_v2": ['Data Protection:write'],
    "exclusions_create_v2": ['Machine Learning Exclusions:write'],
    "exclusions_delete_v2": ['Machine Learning Exclusions:write'],
    "exclusions_get_all_v2": ['Machine Learning Exclusions:read'],
    "exclusions_get_reports_v2": ['Machine Learning Exclusions:read'],
    "exclusions_get_v2": ['Machine Learning Exclusions:read'],
    "exclusions_perform_action_v2": ['Machine Learning Exclusions:write'],
    "exclusions_search_v2": ['Machine Learning Exclusions:read'],
    "exclusions_update_v2": ['Machine Learning Exclusions:write'],
    "extAggregateClusterAssessments": ['Cloud Security API Assets:read'],
    "extAggregateFailedContainersByRulesPath": ['Cloud Security API Assets:read'],
    "extAggregateFailedContainersCountBySeverity": ['Cloud Security API Assets:read'],
    "extAggregateFailedImagesByRulesPath": ['Cloud Security API Assets:read'],
    "extAggregateFailedImagesCountBySeverity": ['Cloud Security API Assets:read'],
    "extAggregateFailedRulesByClusters": ['Cloud Security API Assets:read'],
    "extAggregateFailedRulesByImages": ['Cloud Security API Assets:read'],
    "extAggregateFailedRulesCountBySeverity": ['Cloud Security API Assets:read'],
    "extAggregateImageAssessments": ['Cloud Security API Assets:read'],
    "extAggregateRulesAssessments": ['Cloud Security API Assets:read'],
    "extAggregateRulesByStatus": ['Cloud Security API Assets:read'],
    "getCIDGroupByIdV2": ['Flight Control:read'],
    "getCIDGroupMembersByV2": ['Flight Control:read'],
    "getChildrenV2": ['Flight Control:read'],
    "getCloudEventIDs": ['CSPM registration:read'],
    "getContentUpdatePolicies": ['Content Update:read'],
    "getDefaultDeviceControlPolicies": ['Device Control Policies:read'],
    "getDefaultDeviceControlSettings": ['Device Control Policies:read'],
    "getDeviceControlPoliciesV2": ['Device Control Policies:read'],
    "getEvaluationLogic": ['Vulnerabilities:read'],
    "getEvaluationLogicMixin0": ['Configuration Assessment:read'],
    "getFirewallPolicies": ['Firewall Management:read'],
    "getPreventionPolicies": ['Prevention Policies:read'],
    "getRTResponsePolicies": ['Response Policies:read'],
    "getRemediationsV2": ['Vulnerabilities:read'],
    "getRulesMetadataByID": ['Kubernetes Protection:read'],
    "getSensorUpdatePoliciesV2": ['Sensor update policies:read'],
    "getServiceArtifacts": ['ASPM:read'],
    "getUserGroupMembersByIDV2": ['Flight Control:read'],
    "getUserGroupsByIDV2": ['Flight Control:read'],
    "getVulnerabilities": ['Vulnerabilities:read'],
    "get_accounts": ['Assets:read'],
    "get_applications": ['Assets:read'],
    "get_ecosystem_subsidiaries": ['Assets:read'],
    "get_events": ['Firewall Management:read'],
    "get_external_assets": ['Assets:read'],
    "get_firewall_fields": ['Firewall Management:read'],
    "get_hosts": ['Assets:read'],
    "get_iot_hosts": ['Assets:read'],
    "get_logins": ['Assets:read'],
    "get_network_locations": ['Firewall Management:read'],
    "get_network_locations_details": ['Firewall Management:read'],
    "get_patterns": ['Custom Ioa:read'],
    "get_platforms": ['Firewall Management:read'],
    "get_policy_containers": ['Firewall Management:read'],
    "get_rule_groupsMixin0": ['Custom Ioa:read'],
    "get_rulesMixin0": ['Custom Ioa:read'],
    "get_rules_get": ['Custom Ioa:read'],
    "incrementUninstallToken": ['Sensor update policies:write'],
    "indicator_combined_v1": ['IOC Management:read'],
    "indicator_get_device_count_v1": ['IOC Management:read'],
    "indicator_get_devices_ran_on_v1": ['IOC Management:read'],
    "indicator_get_processes_ran_on_v1": ['IOC Management:read'],
    "indicator_update_v1": ['IOC Management:write'],
    "ioc_type_query_v1": ['IOC Management:read'],
    "patchDeviceControlPoliciesV2": ['Device Control Policies:write'],
    "patch_external_assets": ['Assets:write'],
    "platform_query_v1": ['IOC Management:read'],
    "postDeviceControlPoliciesV2": ['Device Control Policies:write'],
    "post_external_assets_inventory_v1": ['Assets:write'],
    "post_graphql": ['Identity Protection GraphQL:write'],
    "queries_access_tags_get_v1": ['Case Management:read'],
    "queries_classification_get_v2": ['Data Protection:read'],
    "queries_cloud_application_get_v2": ['Data Protection:read'],
    "queries_content_pattern_get_v2": ['Data Protection:read'],
    "queries_enterprise_account_get_v2": ['Data Protection:read'],
    "queries_fields_get_v1": ['Case Management:read'],
    "queries_file_details_get_v1": ['Case Management:read'],
    "queries_file_type_get_v2": ['Data Protection:read'],
    "queries_local_application_get": ['Data Protection:read'],
    "queries_local_application_group_get": ['Data Protection:read'],
    "queries_notification_groups_get_v2": ['Case Management:read'],
    "queries_policy_get_v2": ['Data Protection:read'],
    "queries_rules_get_v2": ['Correlation Rules:read'],
    "queries_sensitivity_label_get_v2": ['Data Protection:read'],
    "queries_states_v1": ['Device Content:read'],
    "queries_template_snapshots_get_v1": ['Case Management:read'],
    "queries_templates_get_v1Mixin0": ['Correlation Rules:read'],
    "queries_web_location_get_v2": ['Data Protection:read'],
    "queryChanges": ['Filevantage:read'],
    "queryCombinedFirewallPolicies": ['Firewall Management:read'],
    "queryCombinedFirewallPolicyMembers": ['Firewall Management:read'],
    "queryCombinedHostGroups": ['Host Groups:read'],
    "queryContentUpdatePolicies": ['Content Update:read'],
    "queryContentUpdatePolicyMembers": ['Content Update:read'],
    "queryDeviceControlPolicies": ['Device Control Policies:read'],
    "queryDeviceControlPolicyMembers": ['Device Control Policies:read'],
    "queryEvaluationLogic": ['Vulnerabilities:read'],
    "queryFirewallPolicies": ['Firewall Management:read'],
    "queryFirewallPolicyMembers": ['Firewall Management:read'],
    "queryGroupMembers": ['Host Groups:read'],
    "queryPreventionPolicies": ['Prevention Policies:read'],
    "queryPreventionPolicyMembers": ['Prevention Policies:read'],
    "queryRTResponsePolicies": ['Response Policies:read'],
    "queryRTResponsePolicyMembers": ['Response Policies:read'],
    "querySensorUpdatePolicies": ['Sensor update policies:read'],
    "querySensorUpdatePolicyMembers": ['Sensor update policies:read'],
    "queryVulnerabilities": ['Vulnerabilities:read'],
    "query_accounts": ['Assets:read'],
    "query_applications": ['Assets:read'],
    "query_ecosystem_subsidiaries": ['Assets:read'],
    "query_events": ['Firewall Management:read'],
    "query_external_assets_v2": ['Assets:read'],
    "query_firewall_fields": ['Firewall Management:read'],
    "query_hosts": ['Assets:read'],
    "query_iot_hostsV2": ['Assets:read'],
    "query_logins": ['Assets:read'],
    "query_network_locations": ['Firewall Management:read'],
    "query_patterns": ['Custom Ioa:read'],
    "query_platforms": ['Firewall Management:read'],
    "query_rule_groupsMixin0": ['Custom Ioa:read'],
    "query_rulesMixin0": ['Custom Ioa:read'],
    "retrieveUser": ['User Management:read'],
    "schedule_scan": ['Ods:write'],
    "severity_query_v1": ['IOC Management:read'],
    "ss_ioa_exclusions_create_v2": ['IOA Exclusions:write'],
    "ss_ioa_exclusions_delete_v2": ['IOA Exclusions:write'],
    "ss_ioa_exclusions_get_reports_v2": ['IOA Exclusions:read'],
    "ss_ioa_exclusions_get_v2": ['IOA Exclusions:read'],
    "ss_ioa_exclusions_matched_rule_v2": ['IOA Exclusions:write'],
    "ss_ioa_exclusions_new_rules_v2": ['IOA Exclusions:write'],
    "ss_ioa_exclusions_search_v2": ['IOA Exclusions:read'],
    "ss_ioa_exclusions_update_v2": ['IOA Exclusions:write'],
    "updateDefaultDeviceControlPolicies": ['Device Control Policies:write'],
    "updateDefaultDeviceControlSettings": ['Device Control Policies:write'],
    "update_network_locations": ['Firewall Management:write'],
    "update_network_locations_metadata": ['Firewall Management:write'],
    "update_network_locations_precedence": ['Firewall Management:write'],
    "update_policy_container_v1": ['Firewall Management:write'],
    "update_rule_group_validation": ['Firewall Management:write'],
    "upsert_network_locations": ['Firewall Management:write'],
    "v1_child_executions_query": ['Workflow:read'],
    "validate": ['Custom Ioa:write'],
    "validate_filepath_pattern": ['Firewall Management:write'],
}
