name: Markdown Lint

on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe
      with:
        config: '.markdownlint.json'
        globs: |
          README.md
          docs/**/*.md
