name: Python Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@39eb6c9dde236bbc368681611e63120a6eb4afac
        with:
          version: "0.7.13"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Lint imports
        run: |
          ruff check . --select I

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Type check with mypy
        run: |
          uv run mypy .
